############
# 기본 설정들 #
############

create_new_folder : True

image_number : 0

# 찍힐 사진의 해상도를 정해주자
resolution: {
  width: 480,
  height: 270
}

# 총 찍을 사진의 개수를 정해주자
total_images: 200

# 몇초에 한번씩 찍을것인지 정해주자
interval: 5.0

# ISO 값 설정. 0 = 자동, 60~800 까지 직접 설정 가능
iso: 0

# 사진의 밝기 설정
brightness: 60

# 셔터 스피드 설정. 0 = 자동, 직접 값은 microseconds로 입력( 1s = 1000000 * 1ms )
shutter_speed: 0

# 색보정. https://ko.wikipedia.org/wiki/%EC%83%89%EC%A1%B0%ED%99%94 참고. 비워두면 자동으로 정해줌.
white_balance: {}
  # red_gain: 1.3
  # blue_gain: 1.75

# 찍은 사진을 돌린다. 0도, 90도, 180도, 270도 회전
rotation: 0